package order

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/TBD54566975/tbdex-go/tbdex/closemsg"
	"github.com/TBD54566975/tbdex-go/tbdex/crypto"
	"github.com/TBD54566975/tbdex-go/tbdex/message"
	"github.com/TBD54566975/tbdex-go/tbdex/orderstatus"
	"github.com/TBD54566975/tbdex-go/tbdex/validator"
	"github.com/tbd54566975/web5-go/dids/did"
	"go.jetpack.io/typeid"
)

// Kind is the value used within a message's metadata.kind
const Kind = "order"

// ValidNext returns the valid message kinds that can follow an order.
func ValidNext() []string {
	return []string{orderstatus.Kind, closemsg.Kind}
}

// Order represents a tbdex [order] message.
//
// [order]: https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#order
type Order struct {
	Metadata  message.Metadata `json:"metadata,omitempty"`
	Data      Data             `json:"data,omitempty"`
	Signature string           `json:"signature,omitempty"`
}

// GetMetadata returns the metadata of the message
func (o Order) GetMetadata() message.Metadata {
	return o.Metadata
}

// GetKind returns the kind of message
func (o Order) GetKind() string {
	return o.Metadata.Kind
}

// GetValidNext returns the valid message kinds that can follow an order.
func (o Order) GetValidNext() []string {
	return []string{orderstatus.Kind, closemsg.Kind}
}

// IsValidNext checks if the kind is a valid next message kind for an order.
func (o Order) IsValidNext(kind string) bool {
	for _, k := range ValidNext() {
		if k == kind {
			return true
		}
	}
	return false
}
// Data represents the data field of an order message.
// Note that this is intentionally left empty as per the spec
type Data struct{}

// Digest computes a hash of the order
func (o Order) Digest() ([]byte, error) {
	payload := map[string]any{"metadata": o.Metadata, "data": o.Data}

	hashed, err := crypto.DigestJSON(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to compute order digest: %w", err)
	}

	return hashed, nil
}

// Verify verifies the order's signature.
func (o *Order) Verify() error {
	decoded, err := crypto.VerifySignature(o, o.Signature)
	if err != nil {
		return fmt.Errorf("failed to verify order signature: %w", err)
	}

	if decoded.SignerDID.URI != o.Metadata.From {
		return fmt.Errorf("signer: %s does not match message metadata from: %s", decoded.SignerDID.URI, o.Metadata.From)
	}

	return nil
}

// UnmarshalJSON validates and unmarshals the input data into an Order.
func (o *Order) UnmarshalJSON(data []byte) error {
	err := validator.Validate(validator.TypeMessage, data, validator.WithKind(Kind))
	if err != nil {
		return fmt.Errorf("invalid order: %w", err)
	}

	type shadow Order
	ret := shadow{}

	err = json.Unmarshal(data, &ret)
	if err != nil {
		return fmt.Errorf("failed to unmarshal order: %w", err)
	}

	*o = Order(ret)

	return nil
}

// Parse unmarshals the provided input into an Order and then verifies the signature.
func Parse(data []byte) (Order, error) {
	var o Order
	err := json.Unmarshal(data, &o)
	if err != nil {
		return Order{}, fmt.Errorf("failed to unmarshal order: %w", err)
	}

	err = o.Verify()
	if err != nil {
		return o, fmt.Errorf("integrity mismatch: %w", err)
	}

	return o, nil
}

// CreateOption defines a type for functions that can modify the createOptions struct.
type CreateOption func(*createOptions)

type createOptions struct {
	createdAt  time.Time
	id         string
	externalID string
	protocol   string
}

// ID can be passed to [Create] to provide a custom id.
func ID(id string) CreateOption {
	return func(r *createOptions) {
		r.id = id
	}
}

// CreatedAt can be passed to [Create] to provide a custom created at time.
func CreatedAt(t time.Time) CreateOption {
	return func(q *createOptions) {
		q.createdAt = t
	}
}

// ExternalID can be passed to [Create] to provide a external id.
func ExternalID(externalID string) CreateOption {
	return func(q *createOptions) {
		q.externalID = externalID
	}
}

// Create creates a new order message. The following are generated by default unless custom values are provided:
//   - created at time is set to the current time
//   - protocol is set to "1.0"
//   - id is autogenerated
func Create(fromDID did.BearerDID, to, exchangeID string, opts ...CreateOption) (Order, error) {
	options := createOptions{
		id:        typeid.Must(typeid.WithPrefix(Kind)).String(),
		createdAt: time.Now(),
		protocol:  "1.0",
	}

	for _, o := range opts {
		o(&options)
	}

	o := Order{
		Metadata: message.Metadata{
			From:       fromDID.URI,
			To:         to,
			Kind:       Kind,
			ID:         options.id,
			ExchangeID: exchangeID,
			CreatedAt:  options.createdAt.UTC().Format(time.RFC3339),
			ExternalID: options.externalID,
			Protocol:   options.protocol,
		},
		Data: Data{},
	}

	signature, err := crypto.Sign(o, fromDID)
	if err != nil {
		return Order{}, fmt.Errorf("failed to sign order: %w", err)
	}

	o.Signature = signature

	return o, nil
}
