on:
  push:
    branches:
      - main
  pull_request:
name: CI
concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
        with:
          cache: true

      - name: Build Cache
        uses: ./.github/actions/build-cache

      - name: Test
        run: just test

      - name: Upload Tbdex Go Test Results
        uses: actions/upload-artifact@v3
        with:
          name: go-test-results
          path: '**/report.xml'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: 'true'

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
        with:
          cache: true

      - name: Build Cache
        uses: ./.github/actions/build-cache
        
      - name: Lint
        run: just lint
